site_author: Edu
site_name: 
  - Edu-mkdocs
  - Práctica 1.3-Mi primera práctica en Mkdocs-GitHub Pages
  - Práctica 2.1-Implantación de una web estática con Apache en markdown
  - Práctica 2.2-Creación y configuración de un certificado SSL/TLS autofirmado en Apache
  - Práctica 2.3-Instalar, configurar y securizar phpMyAdmin
  - Práctica 2.4-Instalar y configurar Wordpress
nav:
  - Inicio: index.md
  - Práctica 1.3:
    - Detalle: 
      - Práctica 1.3/Paso1.md
      - Práctica 1.3/Paso2.md
  - Práctica 2.1:
    - Detalle técnico: 
      - Práctica 2.1/Documento técnico.md
  - Práctica 2.2:
    - Detalle técnico:
      - Práctica 2.2/Documento técnico.md
  - Práctica 2.3:
    - Detalle informativo:
      - Práctica 2.3/Documento-informacion.md
  - Práctica 2.4:
    - Detalle documento:
      - Práctica 2.4/Documento detallado.md  
docs_dir: docs
site_dir: site
theme:
  name: material
  language: es
  features:
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: edu 2024
