site_author: Edu
site_name: Edu-mkdocs
site-description: Instalar, configurar y securizar phpMyAdmin
nav:
  - Inicio: index.md
  - Documento explicativo: Documento-informacion.md
theme:
  name: material
  language: es
  features:
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      sheme: default
      primary: indigo
      accent: purle
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
mardown_extensions:
  - codehilite:
      guess_lang: false
      linemus: true

  - pymdownx.highlight:
      anchor_linemus: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

copyright: edu 2024

